apiVersion: v1
kind: Service
metadata:
  name: collector
spec:
  type: NodePort
  selector:
    app: collector
  ports:
  - port: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  labels:
    app: collector
spec:
  selector:
    matchLabels:
      app: collector
  replicas: 1
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: urosv/car-watcher-collector:1.0.4
        ports:
        - containerPort: 3000
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: ['sh', '-c', "while [[ $(kubectl get pods -l app=collectordb -o 'jsonpath={..status.conditions[?(@.type==\"Ready\")].status}') != \"True\" ]]; do echo \"waiting for database\" && sleep 15; done"]
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command: ['sh', '-c', "while [[ $(kubectl get pods -l app=rabbitmq-mqtt-time -o 'jsonpath={..status.conditions[?(@.type==\"Ready\")].status}') != \"True\" ]]; do echo \"waiting for rabbitmq\" && sleep 15; done"]
